# Generated by Django 4.2.30 on 2026-07-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_type', models.CharField(choices=[('ON_GRID', 'On Grid'), ('OFF_GRID', 'Off Grid'), ('HYBRID', 'Hybrid')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('MATERIAL_ASSIGNED', 'Material Assigned'), ('INSTALLATION_STARTED', 'Installation Started'), ('STRUCTURE_INSTALLED', 'Structure Installed'), ('PANELS_INSTALLED', 'Panels Installed'), ('INVERTER_INSTALLED', 'Inverter Installed'), ('WIRING_COMPLETED', 'Wiring Completed'), ('TESTING_COMPLETED', 'Testing Completed'), ('COMMISSIONED', 'Commissioned'), ('COMPLETED', 'Completed')], default='CREATED', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='customers.customer')),
            ],
        ),
    ]
