# Generated by Django 4.2.30 on 2026-07-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='capacity',
            new_name='capacity_kw',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_type',
            new_name='installation_type',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_id',
            new_name='project_code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_technician',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('NEW', 'New'), ('SURVEY_DONE', 'Survey Done'), ('MATERIAL_READY', 'Material Ready'), ('INSTALLATION_IN_PROGRESS', 'Installation In Progress'), ('TESTING', 'Testing'), ('COMPLETED', 'Completed')], default='NEW', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255),
        ),
    ]
