# Generated by Django 4.2.30 on 2026-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lead_source', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('SURVEY_SCHEDULED', 'Survey Scheduled'), ('QUOTATION_SENT', 'Quotation Sent'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
