# Generated by Django 4.2.30 on 2026-07-30 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='alternative_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer_category',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('INDUSTRIAL', 'Industrial'), ('AGRICULTURAL', 'Agricultural'), ('COMMERCIAL', 'Commercial'), ('GOVERNMENT', 'Government')], default='RESIDENTIAL', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='reference_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('WEBSITE', 'Website'), ('REFERENCE', 'Reference'), ('WALK_IN', 'Walk In'), ('BROKER', 'Broker'), ('EXISTING_CUSTOMER', 'Existing Customer'), ('MARKETING_CAMPAIGN', 'Marketing Campaign'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='project_type',
            field=models.CharField(choices=[('ON_GRID', 'On Grid'), ('OFF_GRID', 'Off Grid'), ('HYBRID', 'Hybrid')], default='ON_GRID', max_length=50),
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('followup_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('next_action', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='crm.lead')),
            ],
        ),
    ]
