# Generated by Django 4.2.30 on 2026-07-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_alternative_mobile_lead_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='remarks',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='assigned_to',
            new_name='sales_person',
        ),
        migrations.RenameField(
            model_name='leadfollowup',
            old_name='notes',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='reference_mobile',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='reference_name',
        ),
        migrations.RemoveField(
            model_name='leadfollowup',
            name='followup_time',
        ),
        migrations.RemoveField(
            model_name='leadfollowup',
            name='next_action',
        ),
        migrations.RemoveField(
            model_name='leadfollowup',
            name='status',
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='customer_category',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('AGRICULTURAL', 'Agricultural'), ('GOVERNMENT', 'Government')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('WEBSITE', 'Website'), ('REFERENCE', 'Reference'), ('WALK_IN', 'Walk In'), ('WHATSAPP', 'WhatsApp'), ('BROKER', 'Broker'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='project_type',
            field=models.CharField(choices=[('ON_GRID', 'On Grid'), ('OFF_GRID', 'Off Grid'), ('HYBRID', 'Hybrid')], max_length=50),
        ),
    ]
