# Generated by Django 4.2.30 on 2026-07-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_alternative_mobile_lead_assigned_to_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='customer_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='village',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_category',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('AGRICULTURAL', 'Agricultural'), ('GOVERNMENT', 'Government')], default='COMMERCIAL', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.lead'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
