# Generated by Django 4.2.30 on 2026-07-30 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_capacity_project_capacity_kw_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('PANEL', 'Solar Panel'), ('INVERTER', 'Inverter'), ('BATTERY', 'Battery'), ('STRUCTURE', 'Structure'), ('CABLE', 'Cable'), ('OTHER', 'Other')], max_length=50)),
                ('unit', models.CharField(default='NOS', max_length=50)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_to', models.CharField(max_length=200)),
                ('issued_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='stockreceipt',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='MaterialAllocation',
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
        migrations.DeleteModel(
            name='StockReceipt',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
