# Generated by Django 4.2.30 on 2026-07-30 14:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_capacity_project_capacity_kw_and_more'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed')], default='ASSIGNED', max_length=50)),
                ('assigned_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectupdate',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectupdate',
            name='technician',
        ),
        migrations.RenameField(
            model_name='technician',
            old_name='employee_id',
            new_name='technician_code',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='email',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='name',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='region',
        ),
        migrations.AddField(
            model_name='technician',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='technician_name',
            field=models.CharField(default='Default Technician', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectAssignment',
        ),
        migrations.DeleteModel(
            name='ProjectUpdate',
        ),
        migrations.AddField(
            model_name='workorder',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technicians.technician'),
        ),
    ]
