# Generated by Django 4.2.30 on 2026-07-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('ELECTRICITY_BILL', 'Electricity Bill'), ('PROPERTY_DOCUMENT', 'Property Document'), ('SITE_PHOTO', 'Site Photo'), ('QUOTATION', 'Quotation'), ('SIGNED_DOCUMENT', 'Signed Document'), ('SUBSIDY_DOCUMENT', 'Subsidy Document'), ('INSPECTION_REPORT', 'Inspection Report'), ('OTHER', 'Other')], max_length=100)),
                ('document_name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='customer_documents/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
            ],
        ),
    ]
