# Generated by Django 4.2.30 on 2026-07-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdocument',
            name='file',
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='file_path',
            field=models.CharField(default='/documents/default.pdf', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='document_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='document_type',
            field=models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('ELECTRICITY_BILL', 'Electricity Bill'), ('SITE_SURVEY', 'Site Survey'), ('PROPERTY_DOC', 'Property Document'), ('QUOTATION', 'Quotation'), ('AGREEMENT', 'Agreement'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
