# Generated by Django 4.2.30 on 2026-07-30 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='capacity',
            new_name='capacity_kw',
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(default='TEMP00001', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='subsidy_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='installation_mode',
            field=models.CharField(choices=[('ON_GRID', 'On Grid'), ('OFF_GRID', 'Off Grid'), ('HYBRID', 'Hybrid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='project_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('INDUSTRIAL', 'Industrial'), ('AGRICULTURAL', 'Agricultural')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='installation_mode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='project_type',
            field=models.CharField(max_length=50),
        ),
    ]
