# Generated by Django 4.2.30 on 2026-07-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_rename_capacity_quotation_capacity_kw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='project_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('GOVERNMENT', 'Government'), ('INDUSTRIAL', 'Industrial'), ('AGRICULTURAL', 'Agricultural')], max_length=50),
        ),
    ]
